site_name: Scaffold
site_url: https://hay-kot.github.io/scaffold/
repo_name: Scaffold
repo_url: https://github.com/hay-kot/scaffold
use_directory_urls: true
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs.sticky

plugins:
  - tags
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
